// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package piya.com.repay.domain;

import org.springframework.beans.factory.annotation.Configurable;
import piya.com.repay.domain.Ad_user;

privileged aspect Ad_user_Roo_Configurable {
    
    declare @type: Ad_user: @Configurable;
    
}
